#1

При запуску py . в консоль появився такий результат:
We are in the __main__
2021-09-30 15:22:44.263465
win32
test