#1

При запуску py . в консоль появився такий результат:
We are in the __main__
2021-09-30 15:22:44.263465
win32
test

#2

При запуску py . -h в консоль появився такий результат:
usage: . [-h] [-o OPT] [-l]

Приклад передачі аргументів у Python програму.

optional arguments:
  -h, --help            show this help message and exit
  -o OPT, --optional OPT
                        Цей параметр є вибірковим.
  -l, --logs            Якщо виконати команду з цим параметром будуть виводитись логи.

#3

При запуску python . -o "Цей текст також має вивестись" в консоль появився такий результат:
We are in the __main__
2021-09-30 15:27:34.147437
win32
З консолі було передано аргумент
 ========== >> Цей текст також має вивестись << ==========
test

#4 

При запуску python . --logs в консоль появився такий результат:
2021-09-30 15:31:49,002 root INFO: Тут буде просто інформативне повідомлення
2021-09-30 15:31:49,002 root WARNING: Це Warning повідомлення
2021-09-30 15:31:49,003 root ERROR: Це повідомлення про помилку
test

#5

Підчас вводу даних команд були виведені такі дані:

python3 . -o True
We are in the __main__
2021-09-30 16:21:59.691154
win32
Парні числа:  2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100  
test

python3 . -o False
We are in the __main__
2021-09-30 16:22:39.635001
win32
Непарні числа:  1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 
test

We are in the __main__
2021-09-30 16:28:49.685402
win32
Trying operation 27/0...
2021-09-26 20:53:18,854 root ERROR: Error occured!
test

We are in the __main__
2021-09-30 16:28:49.608400
win32
Trying operation 22/1...
2021-09-26 20:53:20,085 root INFO: Error didn`t occured
test
